config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users do
    resource :profile
  end
  
  resources :recipies
  
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'antarctica', to: 'pages#antarctica'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    # Contact form validations
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :meals
  has_many :recipies, through: :meals
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :recipy
  belongs_to :ingredient
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_one_attached :avatar
                    # the following are paperclip specific, need updating for activestorage
                    # :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    # :default_url => "/images/:style/missing.png"
  # validates_acceptance_of :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/recipy.rb
class Recipy < ActiveRecord::Base
  has_many :meals
  has_many :ingredients, through: :meals
  has_one_attached :avatar
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    # GET request to /contact-us
    # Show new contact form
    def new
        @contact = Contact.new
    end
    
    # POST request to /contacts
    def create
        # Mass assignment of form fields into contact object
        @contact = Contact.new(contact_params)
        # Save the contact object to the database
        if @contact.save
            # Store formfields via parameters, into the variables
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            
            # Plug parameters into the Contact Mailer email and send email
            ContactMailer.contact_email(name, email, body).deliver
            
            # Store success message in flash hash and redirect to new action.
            flash[:success] = "Thank you for your message!"
            redirect_to new_contact_path
        else
            # If contact object doesn't save, store errors in flash hash
            # and redirect to the new action
            flash[:danger] = "Error Occured! #{@contact.errors.full_messages.join(", ")}"
            redirect_to new_contact_path
        end
    end
    
    private
        # To collect data from form we need to use strong parameters
        # and whitelist the form fields
        def contact_params
            params.require(:contact).permit(:name, :email, :comments)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end
    
    def antarctica
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  #Get to users/user_id/profile/new
  def new
    @profile = Profile.new
  end
  
  #POST request to /users/:user_id/profile
  def create
    # Ensure that we have the user who is filling out form
    @user = User.find( params[:user_id] )
    # Create profile linked to this specific user
    @profile = @user.build_profile( profile_params )
    if @profile.save
      flash[:success] = "Profile updated!"
      redirect_to user_path( params[:user_id] )
    else
      render action: :new
    end
  end
  
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :avatar, :description)
    end
end

app/controllers/recipies_controller.rb
class RecipiesController < ApplicationController
  
  def new
    @recipy = Recipy.new
  end
  
  def create
    @recipy = Recipy.new(recipy_params)
    if @recipy.save
      flash[:success] = "New Recipe Created"
      redirect_to recipies_path
    else
      flash[:danger] = "Recipe not saved! #{@recipy.errors.full_messages.join(", ")}"
      render action: :new
    end
  end
    
  def show
    @recipy = Recipy.find_by( id: params[:id] )
  end
  
  def index
  end
  
  private
    def recipy_params
      params.require(:recipy).permit(:name, :description, :avatar)
    end
  
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # GET to /users/:id
  def show
    @user = User.find( params[:id] )
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def job_title_icon
    if @user.profile.first_name == "First"
      "<i class='fa fa-code'></i>".html_safe
    end  
  end 
  
end

app/views/contacts/new.html.erb
<div class="contact-page container">
  <div class="row">
    <div class="col-md-4">
      <h1>Contact Form</h1>
      
      <div class="well">
        <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control', placeholder: 'Comments' %>
          </div>
          
          <%= f.submit 'Submit' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WFD</title>
  <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=IM+Fell+Great+Primer" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark">
    <%= link_to "WFD", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %><span class="sr-only">(current)</span>
        </li>
        <li class="nav-item">
          <%= link_to "Contact Us", new_contact_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav mr-right">
        <% if user_signed_in? %>
          <% if current_user.profile %>
            <li class="nav-item active">
              <%= link_to "#{current_user.profile.first_name}", user_path(id: current_user.id), class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to "Create Profile", new_user_profile_path(user_id: current_user.id), class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  
  <div class="container flash-messages">
    <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{type}" %>
    <% end %>
  </div>
  
  <%= yield %>
  
</body>
</html>

app/views/pages/about.html.erb
<div class="about-page text-center container-fluid">
  <h1>About Page</h1>
  <h3>Making cooking easy</h3>
</div>

app/views/pages/antarctica.html.erb
<div class="ant-page text-center container-fluid">
    <h1>Antarctia 2018</h1>
    <h3>Why I want to go</h3>

    <p>My mother is a strong believer in environmental conservation, and as a
    result from a young age I had a keen interest in the environment.</p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
  <h1>What's For Dinner</h1>
  <h3>Plan, Prepare, Produce</h3>
  
  <h3><%= link_to "Let's get cooking", recipies_path, class: 'home-link' %></h3>
  
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <p class="text-center">Be a part of the WFD community and fill out your profile!</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/recipies/_form.html.erb
<%= form_for @recipy do |f| %>
  <div class="form-group">
    <%= f.label :recipe_name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Recipe", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/recipies/index.html.erb
<h1>List of Recipies</h1>

<div class="container">
  <div class="card-columns">
    <% Recipy.all.each do |recipy| %>
      <div class="card">
        <%= image_tag recipy.avatar, class: 'card-img-top' %>
        <div class="card-body">
          <h5 class"card-title"><%= recipy.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted">Subheading</h6>
          <p class="card-text"><%= recipy.description %></p>
          <%= link_to "View", recipy_path(recipy), class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipies/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">New Reicipe</h1>
    <p class="text-center">Create a new recipe here!</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/recipies/show.html.erb
<div class="recipy-page" style="height:100vh">
  <div class="container" style="padding-top:30px">
    <header class="recipy-header">
      <div class="media">
        <%= image_tag @recipy.avatar, class: 'mr-3 recipy-show-image' %>
        <div class="media-body">
          <h3 class="mt-0"><%= @recipy.name %></h3>
          <h5><%= link_to "Save", "#", class: "btn btn-primary" %></h5>
          <%= @recipy.description %>
        </div>
      </div>
    </header>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 text-center">
      <%= image_tag @user.profile.avatar, class: 'avatar-show-img' %>
    </div>
    <div class="col-md-6 name-show">
      <h1><span><%= job_title_icon %></span><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
      <div class="well profile-block">
        <%= @user.profile.description %>
      </div>
    </div>
  </div>
</div>